# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache C:/Users/atul/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-45908-machine/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xczu7ev-ffvf1517-1LV-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/wb_soc_soccom/wb_soc_soccom.cache/wt [current_project]
set_property parent.project_path E:/wb_soc_soccom/wb_soc_soccom.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/wb_soc_soccom/wb_soc_soccom.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_defines.v
set_property file_type "Verilog Header" [get_files E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_defines.v]
read_verilog -library xil_defaultlib -sv {
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/header/wb_soc_functions.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/header/wb_soc_config.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/wb_bus_b3/wb_bus_b3.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/wb_bus_b3/wb_decode.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/wb_bus_b3/wb_interconnect_arb_rr.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/wb_bus_b3/wb_mux.sv
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/top/wb_top.sv
}
read_verilog -library xil_defaultlib {
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/fir/FIR_filter.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/iir/IIR_filter.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/aes/aes_192.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/aes/aes_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/crp.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/des3.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/des3_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/dft/dft_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/dft/dft_top_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/fir/fir_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/idft/idft_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/idft/idft_top_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/dsp/iir/iir_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/key_sel3.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/md5/md5_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/md5/pancham.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/md5/pancham_round.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/picorv32/picorv32.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/picorv32/picorv32_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/raminfr.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/aes/round.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox1.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox2.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox3.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox4.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox5.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox6.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox7.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/des3/sbox8.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/sha256/sha256.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/sha256/sha256_k_constants.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/sha256/sha256_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/sha256/sha256_w_mem.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/crypto/aes/table.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_receiver.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_regs.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_rfifo.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_sync_flops.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_tfifo.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_top.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_transmitter.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/uart/uart_wb.v
  E:/wb_soc_soccom/wb_soc_soccom.srcs/sources_1/imports/RTL/ram/wbram.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/wb_soc_soccom/wb_soc_soccom.srcs/constrs_1/imports/header/wb_soc_constraints.xdc
set_property used_in_implementation false [get_files E:/wb_soc_soccom/wb_soc_soccom.srcs/constrs_1/imports/header/wb_soc_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xczu7ev-ffvf1517-1LV-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
