# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache E:/axi_soc_soccom/.Xil/Vivado-38588-machine/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xczu7ev-ffvf1517-1LV-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/axi_soc_soccom/axi_soc_soccom.cache/wt [current_project]
set_property parent.project_path E:/axi_soc_soccom/axi_soc_soccom.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/axi_soc_soccom/axi_soc_soccom.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_defines.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/top/orpsoc-defines.sv
}
set_property file_type "Verilog Header" [get_files E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_defines.v]
set_property file_type "Verilog Header" [get_files E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/top/orpsoc-defines.sv]
read_verilog -library xil_defaultlib -sv {
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/aes/aes_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/src/axi_address_resolver.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/src/axi_arbiter.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/src/axi_pkg.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/src/axi_intf.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/src/axi_lite_xbar.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/des3_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/dft/dft_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/fir/fir_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/idft/idft_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/iir/iir_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/md5/md5_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/top/picorv32_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/sha256/sha256_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/ram/wbram_top_axi4lite.sv
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/top/axi_soc.sv
}
read_verilog -library xil_defaultlib {
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/dsp/fir/FIR_filter.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/dsp/iir/IIR_filter.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/aes/aes_192.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/aes/aes_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/clkgen/clkgen.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/crp.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/des3.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/des3_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/dsp/dft/dft_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/dft/dft_top_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/fir/fir_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/dsp/idft/idft_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/idft/idft_top_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/dsp/iir/iir_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/key_sel3.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/md5/md5_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/md5/pancham.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/md5/pancham_round.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/picorv32-master/picorv32.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/raminfr.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/aes/round.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox1.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox2.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox3.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox4.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox5.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox6.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox7.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/des3/sbox8.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/sha256/sha256.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/sha256/sha256_k_constants.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/sha256/sha256_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/sha256/sha256_w_mem.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/aes/table.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_receiver.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_regs.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_rfifo.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_sync_flops.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_tfifo.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_top.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_transmitter.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/uart/uart_wb.v
  E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/ram/wbram.v
}
read_vhdl -library xil_defaultlib E:/axi_soc_soccom/axi_soc_soccom.srcs/sources_1/imports/hdl_cores/bonfire_axi4l2wb/bonfire_axi4l2wb.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/axi_soc_soccom/axi_soc_soccom.srcs/constrs_1/imports/header/axi_soc_constraints.xdc
set_property used_in_implementation false [get_files E:/axi_soc_soccom/axi_soc_soccom.srcs/constrs_1/imports/header/axi_soc_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top axi_top -part xczu7ev-ffvf1517-1LV-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef axi_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file axi_top_utilization_synth.rpt -pb axi_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
